### ISSUE TITLE
The computer completely freezes when using DaVinci Resolve's Camera Tracker.

### ISSUE THREAD

**Issue by characharm** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#742]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

DaVinci Resolve 18.6.5

### Processor / Processor Number [Required]

AMD Ryzen 5800X3D

### Graphic Card [Required]

A770 16GB

### GPU Driver Version [Required]

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

N/A

### Description and steps to reproduce [Required]

When attempting to use the Camera Tracker, the computer completely freezes within a few seconds. The mouse stops moving, and there's no response to pressing Caps Lock or Num Lock on the keyboard. After a while, the mouse cursor becomes responsive again, but the computer remains entirely unresponsive overall.

What I've tried:

DaVinci Resolve 18.6.4 or 18.6.5, with various video clips of different formats.
Tried rolling back the driver to 5074.
Checked the computer's stability with memtest64 for several hours.
Deliberately lowered the operating frequencies of the CPU and memory to rule out their instability.
Changed settings in DaVinci Resolve, disabled encoding acceleration, increase or decrease cache settings 
The only thing that fixes the issue is disabling GPU acceleration in the settings of the Camera Tracker tool.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/123120856/2e8baab1-fda1-4244-b2e3-f8ecb99eee56)

**Comment by Gabriela-Intel** [comment]
Hi @characharm! Sorry for the delayed response on this. I was also able to reproduce the issue on my end so I filed a bug sighting for it (id 14022002559). I'll post here when I see any updates on the issue.

Thanks so much for reporting!

**Comment by rmorera-intel** [comment]
Hi @characharm 
This should be fixed now with latest driver [32.0.101.5768](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html), please give it a shot and let us know.

Best Regards,

**Comment by Gabriela-Intel** [comment]
Hey there @characharm. Have you had the chance to check this out yet?

**Comment by characharm** [comment]
> Hey there @characharm. Have you had the chance to check this out yet?

I'll give you feedback very soon

**Comment by characharm** [comment]
Bug is not fixed, the computer freezes in exactly the same way

**Comment by Gabriela-Intel** [comment]
Apologies, looks like that was a false alarm.. The bug is open and is being looked into. I'll update again here once I have something to share.

**Comment by Bill171** [comment]
Hi. Any progress update on this bug?
It is still freezing with latest driver 32.0.101.6299 and DaVinci Resolve 19.1. It's also happening when using Planar Tracker and sometime Magic Mask effect, so not just Camera Tracker.

**Comment by Gabriela-Intel** [comment]
Hi! Thanks for your patience. I know the amount of time this is taking is definitely not ideal.. I do see updates on the bug from last week, so it's still getting worked on.

As for the system freeze with Planar Tracker, I was previously told this one was fixed so I'll double check on a system and report it if it's not.

Thanks for hanging in there.

**Comment by Gabriela-Intel** [comment]
Hey there. I gave it a go on the system I originally was able to replicate on when the bug was first reported using our latest driver ([101.6314](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html), released yesterday) and DaVinci Resolve Studio 19.1.1 and both Camera Tracker and Planar Tracker work fine. 

Can you DDU and try the latest driver?

**Comment by SavageWaffle** [comment]
Has this been resolved, can we close?

**Comment by Felipe-Intel** [comment]
@SavageWaffle we are still waiting to hear from the OP
@Bill171 could you please confirm it the issue is gone with the [latest driver](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?

**Comment by characharm** [comment]
I just checked, and while the CPU load is really high right now (higher than before), the good news is the computer didn't freeze up. GPU load was only around 15-20%, and I've got all the GPU acceleration and Intel optimizations turned on in Resolve.
